### ISSUE TITLE
Retry Google Drive uploads when a 500 error occurs

### ISSUE THREAD

**Issue by DavidBerdik** [DavidBerdik/InfiniDrive#16]
In cases where an upload fails with a 500 error, InfiniDrive crashes and the upload does not complete.

Error message from the crash:
```
Traceback (most recent call last):
  File "InfiniDrive.py", line 84, in <module>
    driveAPI.store_doc(driveConnect, dirId, str(docNum) + ".docx", mem_doc)
  File "/home/pi/InfiniDrive/driveAPI.py", line 63, in store_doc
    fields = 'id').execute()
  File "/home/pi/.local/lib/python3.5/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/pi/.local/lib/python3.5/site-packages/googleapiclient/http.py", line 851, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 500 when requesting https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&alt=json&fields=id returned "Internal Error">

```

**Comment by DavidBerdik** [comment]
This issue should be fixed in 5e75389884f9df0fab127883c023c5d0b69334a3. This issue will be reopened if necessary.
